### ISSUE TITLE
Bug writing to skyh5

### ISSUE THREAD

**Issue by rlbyrne** [RadioAstronomySoftwareGroup/pyradiosky#137] opened 2021-04-23 00:43 UTC
I am attempting to write a skyh5 file using the write_skyh5 function, and I'm encountering this error:
  File "/opt/anaconda3/lib/python3.7/site-packages/pyradiosky/skymodel.py", line 3505, in write_skyh5
    dgrp["stokes"].attrs["unit"] = self.stokes.unit.name
  File "/opt/anaconda3/lib/python3.7/site-packages/astropy/units/core.py", line 560, in name
    "Can not get names from unnamed units. "
AttributeError: Can not get names from unnamed units. Perhaps you meant to_string()?

**Comment by mkolopanis** [comment] 2021-04-23 14:24
Fascinating. Do you have a lightweight MWE you can make of this? Or at least provide more context about what you were writing out? 

I tend to agree with astropy though we probably want `to_string()` when writing our units to disk. Moreover, why is a stokes array in an unnamed unit state :thinking: maybe it ends up with a erroneous composite unit at some stage.  @bhazelton has seen that before.

**Comment by bhazelton** [comment] 2021-04-23 16:29
So this was an issue that I thought I fixed in a semi-recent PR. The problem is that in the conversions between Jy & K you can end up with a weird unit object (might have been a `CompositeUnit` class rather than just `Unit`?), which causes this error. @rlbyrne are you using the most recent version?

**Comment by bhazelton** [comment] 2021-04-23 16:32
The similar thing I ran into was fixed in #129. Maybe this is another instance that I missed in that PR? I took a different approach in that PR than you're taking in #138. I think it should be discussed and fixed uniformly (either approach is ok with me).

**Comment by rlbyrne** [comment] 2021-04-23 19:37
I am using the most recent version. I think Bryna's probably right that this is an issue with it being a `CompositeUnit` class. I'm using units of Jy/sr.

Here's a MWE:

Ncomponents = 5
stokes = np.zeros((4, 1, 5))
stokes = Quantity(stokes, 'Jy/sr')
freq_array = Quantity([182000000], 'Hz')

skymodel = pyradiosky.SkyModel(
    component_type='healpix',
    spectral_type='flat',
    stokes=stokes,
    freq_array=Quantity([182000000], 'Hz'),
    hpx_inds=np.arange(1, Ncomponents+1),
    hpx_order='nested',
    nside=128
)
skymodel.write_skyh5('/Users/ruby/mwe.skyh5')

**Comment by bhazelton** [comment] 2021-07-06 18:06
Ok this makes sense and my solution in #129 doesn't work because the stokes array should be a composite unit in this case (unlike in that other PR).

**Closed** 2021-07-06 20:57 UTC
Labels: bug
